// ── ErrorCode catalog — รูปแบบ MODULE-NNN ─────────────────
// เพิ่ม code ใหม่ที่นี่เป็นหลัก — service throw `new XxxError(ErrorCode.MODULE_XXX, "...")`

export const ErrorCode = {
  // ── Common ──
  COMMON_NOT_FOUND: "COMMON-001",
  COMMON_DUPLICATE: "COMMON-002",
  COMMON_VALIDATION: "COMMON-003",
  COMMON_CONFLICT: "COMMON-004",
  COMMON_RATE_LIMIT: "COMMON-005",
  COMMON_FORBIDDEN: "COMMON-006",
  COMMON_INTERNAL: "COMMON-007",

  // ── Auth ──
  AUTH_INVALID_CREDENTIALS: "AUTH-001",
  AUTH_TOKEN_EXPIRED: "AUTH-002",
  AUTH_TOKEN_INVALID: "AUTH-003",
  AUTH_FORBIDDEN: "AUTH-004",
  AUTH_LOCKED: "AUTH-005",
  AUTH_DISABLED: "AUTH-006",
  AUTH_CAPTCHA_INVALID: "AUTH-007",
  AUTH_REFRESH_REUSE: "AUTH-008",

  // ── User ──
  USER_NOT_FOUND: "USER-001",
  USER_DUPLICATE_USERNAME: "USER-002",
  USER_DUPLICATE_EMAIL: "USER-003",
  USER_CANNOT_DELETE_SELF: "USER-004",
  USER_LAST_ADMIN: "USER-005",
  USER_INVALID_PASSWORD: "USER-006",

  // ── Role ──
  ROLE_NOT_FOUND: "ROLE-001",
  ROLE_HAS_USERS: "ROLE-002",
  ROLE_IS_SYSTEM: "ROLE-003",
  ROLE_DUPLICATE_NAME: "ROLE-004",

  // ── Module (permission master) ──
  MODULE_NOT_FOUND: "MODULE-001",
  MODULE_DUPLICATE_KEY: "MODULE-002",

  // ── Pole ──
  POLE_NOT_FOUND: "POLE-001",
  POLE_DUPLICATE_NAME: "POLE-002",
  POLE_DUPLICATE_DDNS: "POLE-003",
  POLE_INVALID_GPS: "POLE-006",

  // ── MQTT / Sensor ──
  MQTT_PUBLISH_FAILED: "MQTT-001",
  SENSOR_TYPE_NOT_FOUND: "SENSOR-001",
  SENSOR_TYPE_DISABLED: "SENSOR-002",
  SENSOR_PAYLOAD_INVALID: "SENSOR-003",
  SENSOR_TIMESTAMP_DRIFT: "SENSOR-004",

  // ── Camera clip ──
  CLIP_NOT_FOUND: "CLIP-001",

  // ── Alert ──
  ALERT_NOT_FOUND: "ALERT-001",
  ALERT_ALREADY_RESOLVED: "ALERT-002",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
